### ISSUE TITLE
auto reconnect client on server crash

### ISSUE THREAD

**Issue by leccyril** [ivangfr/springboot-rsocket-webflux-aop#2]
Hi, 

i saw on other repo you manage to auto reconnect client.

How did you do ? 

thank you

**Comment by ivangfr** [comment]
Hi @leccyril , the reconnection implementation was done in this commit https://github.com/ivangfr/springboot-rsocket-webflux-aop/commit/ddafd9a90053c6dd9f4ee33ecba4ecd09fcafc86

**Comment by leccyril** [comment]
hello yes i saw, 

I did'nt have last lib, but just i have to send data in continue and it was my problem, but i amanage to make it work
thank you
